language: php

php:
  - hhvm
  - nightly
  - 7.0
  - 7.1

before_install:
  - "composer self-update"
  - "sudo apt-get install graphviz"

install:
  composer install --no-interaction

script:
  php ./vendor/bin/phing build

after_success:
  php ./vendor/bin/coveralls -v
